source 'https://github.com/EvoIos/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Example
	pod 'EaseUILite', :path => '../'
end
